# Generated by Django 5.1.5 on 2025-03-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='bug_page',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='bug_steps',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feature_priority',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feature_title',
        ),
    ]
